name: MAIN

on:
  push:
    branches:
      - main

jobs:
  docgen:
    runs-on: ubuntu-latest
    container: nimlang/nim
    steps:
      - uses: actions/checkout@v3
      - name: Change Owner of Container Working Directory
        run: chown root:root .
      - name: Install dependencies
        run: nimble install -dy
      - name: Generate documentation
        run: |
          nim doc -o:docs/index.html binarylang.nim
          nim rst2html docs/tutorial.rst
          nim rst2html docs/changelog.rst
          nim rst2html docs/devmanual.rst
          mv docs/htmldocs/* docs/
          rmdir docs/htmldocs
      - name: Run tests
        run: |
          cd tests
          testament pattern "*.nim"
          testament html
          mv testresults.html ../docs
          find . -maxdepth 1 -type f ! -name '*.nim' -delete
          rm -r testresults
      - name: Commit documentation
        run: |
          git config --global user.name 'Stefanos Mandalas'
          git config --global user.email 'sealmove@protonmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add docs
          git commit -am "[skip ci] Update documentation"
          git push
